# Generated by Django 4.1.13 on 2024-01-30 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('password', models.CharField(max_length=25)),
                ('encrypt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=20, unique=True)),
                ('discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20, unique=True)),
                ('discription', models.TextField()),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.domain')),
                ('job_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.job_type')),
            ],
        ),
        migrations.CreateModel(
            name='access_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.documents')),
                ('job_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.job_type')),
            ],
        ),
    ]
