# Generated by Django 5.0.2 on 2024-02-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
